Fix: Display error message for unregistered email on sign-in page.
namesakefyi/namesake-convex pull request #299
Opened 2024-12-19 14:50 UTC by nakul-py

### What changed?
- Added a check to verify if the email exists before attempting the sign-in process.
- Display an error message if the email is not registered, prompting users to register a new account.
- If the email is not found, users are provided with a link to the registration tab for account creation.
- Fixes #296
### Why?

- This change was implemented to improve the user experience by notifying users immediately when they attempt to sign in with an unregistered email.
- Users no longer need to guess why they can't log in or be confused by no feedback, leading to better usability and fewer failed attempts.

2024-12-19 15:10 UTC, evadecker requested changes
Hey @nakul-py! In order to display the error here, we'll need to update the sign in logic on the backend.

You can look at the Convex Auth docs for email validation for more info: https://labs.convex.dev/auth/config/passwords#email-address-validation

2024-12-19 15:10 UTC, evadecker commented on src/routes/_unauthenticated/signin.tsx
> +        error instanceof Error ? error.message : "An unexpected error occurred."
We'll want to keep this as `instanceof ConvexError`.

2024-12-19 15:10 UTC, evadecker commented on src/routes/_unauthenticated/signin.tsx
> +  };
This API endpoint `check-user-exists` doesn't exist! Instead you'll need to set and fetch the error from the sign in flow. You can add a `ConvexError` to support returning whether the email exists or not: https://docs.convex.dev/functions/error-handling/application-errors

2024-12-19 15:13 UTC, evadecker commented
Note you'll also need to add a changeset to this PR! You can do it from the command line with `pnpm changeset`.

2024-12-21 02:40 UTC, kydecker commented on .changeset/polite-monkeys-travel.md
> +fix: Show error when signing in with unregistered email
Thanks for adding a changeset!

2024-12-21 02:40 UTC, kydecker commented on src/routes/_unauthenticated/signin.tsx
> +  const { signIn} = useAuthActions();
Make sure that you run `pnpm check:fix` to fix formatting errors like the space missing here. If you have `formatOnSave` set to `true` in your editor it should make it easier :) — it should also run before you go to commit your changes.

2024-12-21 02:40 UTC, evadecker commented on src/routes/_unauthenticated/signin.tsx
> +  const [error, setError] = useState<string | React.ReactNode | null>(null);
Let's keep this as `string | null` for now.

2024-12-21 02:40 UTC, evadecker commented on src/routes/_unauthenticated/signin.tsx
> +  };
I see what you're trying to do here and it makes sense, but we actually want to test this on the backend in our `/convex` directory.

I did a little bit more research and discovered that Convex Auth doesn't easily surface error codes for use in production, so for this PR let's do a workaround which gets us most of the way there.

1. Eliminate this `checkUserExists` function.
2. Instead of what used to exist in our `catch()`, let's just display a generic message.

```diff
try {
  // Existing signIn function
} catch(error) {
- error instanceof ConvexError ? setError(error.message) : setError(error)
+ setError("Couldn't sign in. Check your information and try again.")
} finally {
  // Existing
}
```

That'll be enough to improve the user experience for now!

2024-12-21 12:42 UTC, nakul-py commented on src/routes/_unauthenticated/signin.tsx
> +  const [error, setError] = useState<string | React.ReactNode | null>(null);
Done

2024-12-21 12:43 UTC, nakul-py commented on src/routes/_unauthenticated/signin.tsx
> +  };
done

2024-12-21 12:44 UTC, nakul-py commented on src/routes/_unauthenticated/signin.tsx
> +  const { signIn} = useAuthActions();
Ok, now i am sure about fixing formatting errors.

2024-12-21 12:55 UTC, nakul-py commented
The output :-  

https://github.com/user-attachments/assets/0354c7b0-7a4e-47c6-a60a-b697a66a3e88

2024-12-21 15:20 UTC, evadecker approved these changes
One tiny change, otherwise looks good! Thanks so much, @nakul-py!

2024-12-21 15:20 UTC, evadecker commented on src/routes/_unauthenticated/signin.tsx
> +      console.error(error);
We can remove this `console.error`

2024-12-22 12:19 UTC, nakul-py commented on src/routes/_unauthenticated/signin.tsx
> +      console.error(error);
Done

2024-12-22 12:19 UTC, nakul-py commented on src/routes/_unauthenticated/signin.tsx
> +      console.error(error);
Done

2024-12-22 12:20 UTC, nakul-py commented
This commit will close this issue https://github.com/namesakefyi/namesake/pull/299/commits/fa90cdf0242bf2cfbaadc04602dbc3c534c7fc4b

2024-12-22 15:10 UTC, merged

2024-12-22 15:10 UTC, evadecker commented
Thanks so much @nakul-py! 💟